### PR TITLE
DLC Agents of Sabotage

### PR DESCRIPTION
**Pull request by TheIndra55**

### CODE REVIEW

**Comment by alberttheprince** [comment]
LGTM

**Review by IOxee — CHANGES_REQUESTED** [review]
The code works correctly.

There are a couple of things missing such as
- MK2 Weapons Workshop
- Subway Garage

**Comment by TheIndra55** [comment]
> There are a couple of things missing such as
> 
> * MK2 Weapons Workshop
> * Subway Garage

The Weapon Workshop is an object that must be spawned, and the garage doesn't have any entity sets.

**Review by IOxee — CHANGES_REQUESTED** [review]
The exterior is correct. The only thing is that there is that pallet there that I don't know if it's a bug of mine or it affects everyone.

image

**Review by Sqrl34 — APPROVED** [review]
lgtm

**Review by IOxee — APPROVED** [review]

**Pull request merged**
