### PR TITLE
More map hole fixes

### PR DESCRIPTION
**Pull request by SirOMGitsYOU**
Fixed Boat House Door in Sandy Shores
Fixed GTA 5 24/7 Roof in Sandy Shores
Fixed Industrial Building near Lesters Warehouse
Fixed Collision Holes near Lost MC compound due to the new casino thanks rockstar.

### CODE REVIEW

**Comment by Bob74** [comment]
Do you have an example of what it fixes (screenshot, video...)?
Recent GTA V updates added/removed some collisions?

**Comment by SirOMGitsYOU** [comment]
> Do you have an example of what it fixes (screenshot, video...)? Recent GTA V updates added/removed some collisions?

Mostly looking at spots that can be massively abused - https://youtu.be/DxTwm8RJ1VU 
https://youtu.be/RPdzgcyqGeA

The lost MC fix can be viewed here is the original pathing in codewalker
image

That slither of a gap between the grass and pavement has been in since the casino update and rockstar are yet to fix this, This can cause people to fall over and infinitely ragdoll and die, This can cause bikes to fall over and explode among a whole host of other issues

**Comment by Bob74** [comment]
Wow alright I see, this game is so messed up :/
Thanks a lot for your work!

**Comment by SirOMGitsYOU** [comment]
>  Wow alright I see, this game is so messed up :/
Thanks a lot for your work!

That's alright :) - The game is truly messed up sadly I don't think they've patched these on the "next next next" gen consoles either sadly I don't have one to test but ah well better late than never haha :D

**Pull request merged**
