### PR TITLE
Update to Tuners DLC

### PR DESCRIPTION
**Pull request by PlanovskyJus**
This doesn't have the same configuration options such as turning interiors on/off in the client.lua, but this is from the suggestion made in Issue 55 by TayMcKenzieNZ https://github.com/Bob74/bob74_ipl/issues/55#issuecomment-944259322 

FULL CREDIT TO @TayMcKenzieNZ  for making this. I tested it and it works great except for the Methlab interior is a bit glitchy.

### CODE REVIEW

**Comment by TayMcKenzieNZ** [comment]
I just found the code online, I wouldn't necessarily say I did much but good to see you tidied it up and everything lol

**Review by AvaN0x — CHANGES_REQUESTED** [review]
Don't the interiors need to be refreshed after changing entity sets and not before?
I might be wrong though.

**Comment by TayMcKenzieNZ** [comment]
Yes, you could be right.

**Comment by TayMcKenzieNZ** [comment]
To be completely honest, the resource needs to be completely written to RequestIPL and RemoveIPL when needed.

**Comment by AvaN0x** [comment]
> To be completely honest, the resource needs to be completely written to RequestIPL and RemoveIPL when needed.

I agree.

**Comment by Bob74** [comment]
Unfortunately it is not written the same way as the rest of the resource at all :/
If it is rewritten to conform to the rest avec the resource, I will gladly add it :)

**Comment by Bob74** [comment]
Added in https://github.com/Bob74/bob74_ipl/pull/73

**Pull request closed without merging**
